# Generated by Django 5.0.3 on 2024-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
