# Generated by Django 5.0.3 on 2024-05-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='vencimiento',
            field=models.CharField(max_length=10),
        ),
    ]
