# Generated by Django 5.0.3 on 2024-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
