# Generated by Django 5.0.3 on 2024-05-28 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_initial'),
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='productos',
        ),
        migrations.CreateModel(
            name='PresupuestoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto_productos', to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
