# Generated by Django 5.0.3 on 2024-05-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_presupuesto_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
