# Generated by Django 5.0.3 on 2024-05-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('presupuestos', '0005_presupuesto_cantidad_presupuesto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='moneda',
            field=models.CharField(max_length=3),
        ),
    ]
