# Generated by Django 5.0.3 on 2024-05-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_alter_presupuestoproducto_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
