# Generated by Django 5.0.3 on 2024-05-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_presupuesto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='total',
        ),
    ]
