# Generated by Django 5.0.3 on 2024-06-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_remove_presupuesto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestoproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
