# Generated by Django 5.0.3 on 2024-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0008_presupuestoproducto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='remitido',
            field=models.BooleanField(default=False),
        ),
    ]
