# Generated by Django 5.0.3 on 2024-04-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('SERVICIO', 'SERVICIO'), ('PRODUCTO', 'PRODUCTO'), ('OTRO', 'OTRO')], max_length=10)),
                ('tasa_iva', models.CharField(choices=[('IVA EXENTO', 'IVA EXENTO'), ('IVA NO GRAVADO', 'IVA NO GRAVADO'), ('0.0', 'IVA 0%'), ('2.5', 'IVA 2.5%'), ('5.0', 'IVA 5%'), ('10.5', 'IVA 10.5%'), ('21.0', 'IVA 21%'), ('27.0', 'IVA 27%')], max_length=17)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('KILO', 'KILO'), ('LITRO', 'LITRO'), ('METRO', 'METRO'), ('OTRO', 'OTRO')], max_length=10)),
                ('precio_venta_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
