# Generated by Django 5.0.3 on 2024-04-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('SERVICIOS', 'SERVICIOS'), ('PRODUCTOS', 'PRODUCTOS'), ('OTRO', 'OTRO')], default='PRODUCTOS', max_length=10)),
                ('tasa_iva', models.DecimalField(choices=[(0, '0%'), (10.5, '10.5%'), (21, 'IVA 21%'), (27, '27%')], decimal_places=2, default=21, max_digits=5)),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'UNIDAD'), ('KILO', 'KILO'), ('LITRO', 'LITRO'), ('METRO', 'METRO'), ('OTRO', 'OTRO')], default='UNIDAD', max_length=10)),
                ('actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_venta_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
