# Generated by Django 5.0.3 on 2024-04-16 00:23

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('CUIL', 'CUIL'), ('CUIT', 'CUIT'), ('DNI', 'DNI'), ('PASAPORTE', 'PASAPORTE'), ('OTRO', 'OTRO')], default='CUIL', max_length=15)),
                ('numero_identificacion', models.CharField(max_length=40)),
                ('otro_identificacion', models.CharField(blank=True, max_length=40, null=True)),
                ('condicion_iva', models.CharField(choices=[('RESPONSABLE INSCRIPTO', 'RESPONSABLE INSCRIPTO'), ('MONOTRIBUTISTA', 'MONOTRIBUTISTA'), ('EXENTO', 'EXENTO'), ('EXTERIOR', 'EXTERIOR'), ('CONSUMIDOR FINAL', 'CONSUMIDOR FINAL'), ('IVA NO ALCANZADO', 'IVA NO ALCANZADO')], default='CONSUMIDOR FINAL', max_length=30)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
