# Generated by Django 5.0.3 on 2024-05-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(max_length=15),
        ),
    ]
