# Generated by Django 5.0.3 on 2024-06-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(max_length=17),
        ),
    ]
